format:
  mintlify-md:
    code-fold: true
metadata-files:
- nbdev.yml
- sidebar.yml
project:
  type: mintlify
website:
  body-footer: 'If you find the code useful, please ‚≠ê us on [Github](https://github.com/nixtla/hierarchicalforecast)

    '
  favicon: favicon_png.png
  google-analytics: G-NXJNCVR18L
  navbar:
    background: primary
    collapse-below: lg
    left:
    - href: examples/TourismSmall.ipynb
      text: Get Started
    - menu:
      - href: https://github.com/nixtla/mlforecast
        text: MLForecast ü§ñ
      - href: https://github.com/nixtla/neuralforecast
        text: NeuralForecast üß†
      - href: https://github.com/nixtla/statsforecast
        text: StatsForecast ‚ö°Ô∏è
      text: NixtlaVerse
    - menu:
      - href: https://github.com/nixtla/hierarchicalforecast/issues/new/choose
        icon: bug
        text: Report an Issue
      - href: https://join.slack.com/t/nixtlacommunity/shared_invite/zt-1kd5m5db7-7OOfy0xVNf1PcvCiAPWvPw
        icon: chat-right-text
        text: Join our Slack
      text: Help
    right:
    - href: https://github.com/nixtla/hierarchicalforecast
      icon: github
    - aria-label: Nixtla Twitter
      href: https://twitter.com/nixtlainc
      icon: twitter
    search: true
  open-graph: true
  repo-actions:
  - issue
  sidebar:
    style: floating
  twitter-card: true
